language: node_js
node_js:
  - "12"
deploy:
  local_dir: build/
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  script: npm run build
  on:
    branch: master
  